FROM openresty/openresty:xenial
RUN opm get SkyLothar/lua-resty-jwt
ADD ac_backend/docker/nginx/nginx.conf.dev /usr/local/openresty/nginx/conf/nginx.conf
ADD ac_backend/docker/nginx/mime.types /usr/local/openresty/nginx/conf/conf/mime.types
ADD ac_backend/docker/nginx/index.html /usr/share/nginx/html/
ADD ac_backend/docker/nginx/jwt-auth.lua /usr/local/openresty/lualib/resty/jwt-auth.lua

EXPOSE 80 8080 8088
ENTRYPOINT ["nginx", "-g", "daemon off;"]