version: '3.9'
services:
  db:
    image: postgres:12.5
    ports:
      - '5432:5432'
    expose:
      - '5432'
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
    environment:
      - POSTGRES_DB=alphacare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ac_backend/docker/nginx/Dockerfile.dev
    ports:
      - '80:80'
      - '8080:8080'
      - '8088:8088'
    depends_on:
      db:
        condition: service_healthy
  user_registry:
    build:
      context: .
      dockerfile: docker/user_registry/Dockerfile
    ports:
      - '50051:50051'
    depends_on:
      db:
        condition: service_healthy
  config_registry:
    build:
      context: .
      dockerfile: docker/config_registry/Dockerfile
    ports:
      - '50052:50052'
    depends_on:
      db:
        condition: service_healthy
  patient_registry:
    build:
      context: .
      dockerfile: docker/patient_registry/Dockerfile
    ports:
      - '50053:50053'
    depends_on:
      db:
        condition: service_healthy
  patient_visit:
    build:
      context: .
      dockerfile: docker/patient_visit/Dockerfile
    ports:
      - '50054:50054'
    depends_on:
      db:
        condition: service_healthy
  notification:
    build:
      context: .
      dockerfile: docker/notification/Dockerfile
    ports:
      - '50055:50055'
  secure_messaging:
    build:
      context: .
      dockerfile: docker/secure_messaging/Dockerfile
    ports:
      - '50056:50056'
    depends_on:
      db:
        condition: service_healthy
  billing:
    build:
      context: .
      dockerfile: docker/billing/Dockerfile
    ports:
      - '50057:50057'
    depends_on:
      db:
        condition: service_healthy
  prescription:
    build:
      context: .
      dockerfile: docker/billing/Dockerfile
    ports:
      - '50058:50058'
    depends_on:
      db:
        condition: service_healthy