app:
    env:  "dev"
    server:
        port: ":50058"
        reversedProxy: "nginx:8080"
    db:
        user: "postgres"
        password: "12345"
        url: "db"
        port: "5432"
        name: "alphacare"