version: '3.9'
services:
  homepage:
    build:
      context: .
      dockerfile: docker/homepage/Dockerfile
    ports:
      - '3000:3000'
  mysql:
    image: mysql:5.7
    container_name: easyappointments-database
    # volumes:
    #     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easyappointments
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  easy_appointments:
    build:
      context: ./apps/easy_appointments/docker/server/
      dockerfile: ../../../../docker/easy_appointments/Dockerfile
    image: easyappointments-server:v1
    ports:
      - "3001:80"
    volumes:
      - ./apps/easy_appointments:/var/www/html
      - ./apps/easy_appointments/docker/server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    depends_on:
      - mysql
