app:
    env:  "beta"
    server:
        port: ":50055"
        reversedProxy: "nginx:8080"
    ses:
        defaultOutgoingEmail: "no-reply@nyxcare.com"
        billingOutgoingEmail: "no-reply@nyxcare.com"
        accountOutgoingEmail: "no-reply@nyxcare.com"